### ISSUE TITLE
Corrections & améliorations session 2 GLIA

### ISSUE THREAD

**Issue by HakumenNC** [adriens/presentation-kafka-connect#1]
* Slide 20 (matrice)
  * Time to Market 
  * Indus.
  * Socle
  * Ajouter lignes : Maintenance (éditeur :montée de version, bugs), Metrics (déjà dispos)

* Slide Monitoring
  * Retirer les grapsh CPU, etc
  * Montrer stats MBEANs
  * Choisir UNE Information communes JMX / json 

* Suite sur solution (voir pricing)

**Comment by HakumenNC** [comment]
Done!

**Comment by adriens** [comment]
😍
